### ISSUE TITLE
feat(harper_ls): add code action to add misspelled word to document's dictionary

### ISSUE THREAD

**Issue by chilipepperhott** [chilipepperhott/harper#30]
Exactly as the title says. I believe that dictionary additions should be document-specific. In other words, additions to the dictionary should not effect other documents.

If we want to be able to add to a global dictionary, that should be a separate code action.

**Comment by mawkler** [comment]
This would be a really great feature to have! I would prefer if harper put all document-specific dictionaries in one single directory rather than in each document's directory, which clutters the file system. One solution to this is what [Neovim does with file-specific so called undofiles](https://neovim.io/doc/user/options.html#'undodir'), which is all lie in `~/.local/share/nvim/` and the file names are the paths to the respective file, with the file-separator replaced with `%`. That being said, I would personally mainly use one single global dictionary.

By the way, is there any way right now to use a custom global dictionary? I.e. can I point harper to a pre-existing file with words that should be white-listed?

**Comment by chilipepperhott** [comment]
I absolutely agree that they should not be in the document's directory. Thanks for pointing me in the direction of those undo files, I wasn't aware of how that worked. Adding these code actions is at the top of my ToDo list.

> By the way, is there any way right now to use a custom global dictionary? I.e. can I point harper to a pre-existing file with words that should be white-listed?

I intend on making the custom global dictionary a plain-text file somewhere on the filesystem. You will be able to edit (and manually append) words to it.

**Comment by mawkler** [comment]
Ok great! As you mentioned in the original issue, a separate code action for appending to the global dictionary as well would be great!

**Comment by chilipepperhott** [comment]
Status update: I've added a globally defined dictionary. Once you update to `harper-ls` v0.7.1 you should start getting code action options to add to it. I'm starting work on file-local dictionaries now.

**Comment by mawkler** [comment]
Awesome! 😄

**Comment by chilipepperhott** [comment]
Another update: as of the most recent versions there are now document-local dictionaries. 

The documentation for the additions from this issue can now be found [here](https://github.com/chilipepperhott/harper/blob/master/harper-ls/README.md).

**Comment by djugei** [comment]
i do not know exactly what changed but in helix i used to have a code action to add a word to the dictionary, this code action does not show up anymore.

additionally words defined in `~/.config/harper-ls/dictionary.txt` do not get ignored.

harper-ls 0.26.0
